language: node_js
notifications:
  email: false
node_js:
  - '10'
  - '11'
script:
  - npm run test:prod && npm run build
after_success:
  - npm run report-coverage
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm publish; fi
services:
  - mongodb
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
